### ISSUE TITLE
Fix Admin Home

### ISSUE THREAD

**Issue by MEDO63B** [MEDO63B/WecareFrontend#14]
### Update **`div`** in `admin.component.scss`

```css
// changes
.content-wrapper[_ngcontent-ng-c11627086] {
height: 100vh;
overflow: scroll;
}
```
